site_name: Minall Documentation

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: "index.md"
  - Tutorials: "tutorials.md"
  - How-To Guides: "how-to-guides.md"
  - "Reference":
      - "root": "reference/root.md"
      - "cli": "reference/cli.md"
      - "utils": "reference/utils.md"
      - "tables": "reference/tables.md"
      - "enrichment":
          - "root": "reference/enrichment.md"
          - "article_text": "reference/enrichment/article_text.md"
  - Explanation: "explanation.md"
