site_name: Minall Documentation

theme:
  name: "material"
  features:
    - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep-purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference

plugins:
  - search
  - autorefs
  - mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: "index.md"
  - Tutorials: "tutorials.md"
  - How-To Guides: "how-to-guides.md"
  - "Reference":
      - "Home": "reference/home.md"
      - "main": "reference/main.md"
      - "cli": "reference/cli.md"
      - "utils": "reference/utils.md"
      - "tables": "reference/tables.md"
      - "enrichment": "reference/enrichment.md"
