site_name: Minall Documentation

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - mkdocstrings

nav:
  - Home: "index.md"
  - Tutorials: "tutorials.md"
  - How-To Guides: "how-to-guides.md"
  - "Reference":
      - "root": "reference/root.md"
      - "cli": "reference/cli.md"
      - "utils": "reference/utils.md"
      - "enrichment":
          - "root": "reference/enrichment.md"
          - "article_text": "reference/enrichment/article_text.md"
  - Explanation: "explanation.md"
