name: Minall Tests

on:
  push:
    paths:
      - "minall/**"
      - "tests/**"

jobs:
  update:
    name: Minall Tests
    runs-on: ubuntu-latest
    env:
      BUZZSUMO_TOKEN: ${{ secrets.BUZZSUMO_TOKEN }}
      CROWDTANGLE_TOKEN: ${{ secrets.CROWDTANGLE_TOKEN }}
      YOUTUBE_KEY: ${{ secrets.YOUTUBE_KEY }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .

      - name: Test Buzzsumo API calls
        run: python -m unittest tests.buzzsumo.Buzzsumo

      - name: Test CrowdTangle API calls
        run: python -m unittest tests.crowdtangle.CTest

      - name: Test tables
        run: python -m unittest tests.table.TableTest

      - name: Test Twitter scraper
        run: |
          python -m unittest tests.twitter.Twitter

      - name: Test YouTube API calls
        run: |
          python -m unittest tests.youtube.YTest
